apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  labels:
    app: zeroshot
# Use stringData for simplicity in dev; converts to base64 at creation
stringData:
  DB_HOST: mysql
  DB_PORT: "3306"
  DB_USER: appuser
  DB_PASSWORD: apppass
  DB_NAME: zeroshot
  DB_ROOT_PASSWORD: rootpass
  
