apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: db-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: zeroshot/db
        property: host
    - secretKey: DB_PORT
      remoteRef:
        key: zeroshot/db
        property: port
    - secretKey: DB_USER
      remoteRef:
        key: zeroshot/db
        property: user
    - secretKey: DB_PASSWORD
      remoteRef:
        key: zeroshot/db
        property: password
    - secretKey: DB_NAME
      remoteRef:
        key: zeroshot/db
        property: name
