apiVersion: v1
kind: ServiceAccount
metadata:
  name: zeroshot-backend-sa
  annotations:
    # Rol IAM creado con eksctl para permitir acceso a Secrets Manager (IRSA)
    eks.amazonaws.com/role-arn: arn:aws:iam::<AWS_ACCOUNT_ID>:role/zeroshot-backend-irsa
